# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMForIS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMForIS
  pod “Alamofire”

  target 'MVVMForISTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMForISUITests' do
    # Pods for testing
  end

end
